[package]
name = "myth"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
pest = "2.7.11"
pest_derive = "2.7.11"
thiserror = "1.0.63"
wasm-encoder = "0.217.0"
wasmprinter = "0.217.0"
wasmtime = "25.0.1"
